name: Build
on:
  push:
    paths:
      - 'src/**'
      - 'buildSrc/**'
      - '**/gradle.properties'
      - '**/settings.gradle.kts'
      - '**/build.gradle.kts'
      - '**/build.*.gradle.kts'
      - 'stonecutter.gradle.kts'
      - 'gradle/**'
      - '.github/workflows/build.yml'
  pull_request:
    branches:
      - 'master'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v6

      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: 25
          cache: gradle

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v6

      - name: Make Gradle Wrapper Executable
        run: chmod +x ./gradlew

      - name: Execute Gradle build
        run: ./gradlew chiseledBuild
